### ISSUE TITLE
Create Basic Vaadin UI to deliver pattern analysis

### ISSUE THREAD

**Issue by matentzn** [obophenotype/phenotypepatternanalysis#10]
Create basic Vaadin UI that builds on services and delivers analysis life. 
- [x] Set up empty Vaadin canvas
- [ ] Load analysis and present hierarchy as lazily loaded graph
- [ ] Present suggestions
- [ ] Allow searching for patterns
- [ ] Deliver as Docker
